
import re
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Dict, Optional, Tuple


# ======================================================================
# SVG namespace
# ======================================================================

SVG_NS = "http://www.w3.org/2000/svg"

ET.register_namespace("", SVG_NS)

NS = {
    "svg": SVG_NS,
}


# ======================================================================
# Basic SVG utilities
# ======================================================================

def numeric_value(value):
    """
    Extract the numerical part of an SVG length.
    """
    if value is None:
        return None

    match = re.match(
        r"\s*([-+]?(?:\d+(?:\.\d*)?|\.\d+)"
        r"(?:[eE][-+]?\d+)?)",
        str(value),
    )

    if match is None:
        return None

    return float(match.group(1))


def get_svg_dimensions(
    root: ET.Element,
) -> Optional[Tuple[float, float, float, float]]:
    """
    Extract (x, y, width, height) from the SVG viewBox.

    Falls back to width/height if no valid viewBox exists.
    """

    viewbox_str = root.attrib.get("viewBox")

    if viewbox_str:

        try:
            parts = [
                float(p)
                for p in re.split(
                    r"[,\s]+",
                    viewbox_str.strip(),
                )
            ]

            if (
                len(parts) == 4
                and parts[2] > 0
                and parts[3] > 0
            ):
                return (
                    parts[0],
                    parts[1],
                    parts[2],
                    parts[3],
                )

        except ValueError:
            pass

    # --------------------------------------------------------------
    # Fallback to width / height
    # --------------------------------------------------------------

    width = numeric_value(
        root.attrib.get("width")
    )

    height = numeric_value(
        root.attrib.get("height")
    )

    if (
        width is not None
        and height is not None
        and width > 0
        and height > 0
    ):
        return 0.0, 0.0, width, height

    return None


# ======================================================================
# Bounding-box handling
# ======================================================================

def remove_existing_bounding_box(
    root: ET.Element,
) -> bool:
    """
    Remove all elements with id="bounding-box".

    Returns True if at least one was removed.
    """

    removed = False

    for parent in root.iter():

        for child in list(parent):

            if child.attrib.get("id") == "bounding-box":

                parent.remove(child)
                removed = True

    return removed


# ======================================================================
# Scaling-group handling
# ======================================================================

SCALING_GROUP_ID = "svg_scaling_group"


def remove_existing_scaling_group(
    root: ET.Element,
) -> bool:
    """
    Remove the scaling group previously generated by this script.

    The group is identified by:

        id="svg_scaling_group"

    Its children are moved back to the root.

    Returns True if a scaling group was removed.
    """

    removed = False

    for child in list(root):

        if child.tag != f"{{{SVG_NS}}}g":
            continue

        if child.attrib.get("id") != SCALING_GROUP_ID:
            continue

        # Preserve the position of the group.
        index = root.index(child)

        children = list(child)

        root.remove(child)

        for offset, grandchild in enumerate(children):
            root.insert(
                index + offset,
                grandchild,
            )

        removed = True

    return removed


# ======================================================================
# Stroke-width extraction
# ======================================================================

def get_stroke_widths(
    root: ET.Element,
):
    """
    Find all explicit stroke-width values in the SVG.

    Searches:
        stroke-width="..."
        style="stroke-width:..."
        <style>...</style>
    """

    stroke_widths = []

    # --------------------------------------------------------------
    # Element attributes and inline styles
    # --------------------------------------------------------------

    for element in root.iter():

        # Direct attribute
        if "stroke-width" in element.attrib:

            value = numeric_value(
                element.attrib["stroke-width"]
            )

            if value is not None:
                stroke_widths.append(value)

        # Inline style
        style = element.attrib.get(
            "style",
            "",
        )

        for match in re.finditer(
            r"stroke-width\s*:\s*([^;}]+)",
            style,
            flags=re.IGNORECASE,
        ):

            value = numeric_value(
                match.group(1)
            )

            if value is not None:
                stroke_widths.append(value)

    # --------------------------------------------------------------
    # <style> elements
    # --------------------------------------------------------------

    for style_element in root.iter(
        f"{{{SVG_NS}}}style"
    ):

        css = style_element.text or ""

        for match in re.finditer(
            r"stroke-width\s*:\s*([^;}]+)",
            css,
            flags=re.IGNORECASE,
        ):

            value = numeric_value(
                match.group(1)
            )

            if value is not None:
                stroke_widths.append(value)

    return stroke_widths


# ======================================================================
# Scale SVG
# ======================================================================

def scale_svg(
    root: ET.Element,
    target_stroke: float = 1.25,
):
    """
    Scale the SVG so that its maximum explicit stroke width becomes
    target_stroke.

    An existing scaling group generated by this script is removed first.

    Returns
    -------
    float
        Applied scale factor.
    """

    # --------------------------------------------------------------
    # Remove scale generated by a previous run.
    # --------------------------------------------------------------

    if remove_existing_scaling_group(root):

        print(
            "  Removed existing scaling group."
        )

    # --------------------------------------------------------------
    # Find stroke widths.
    # --------------------------------------------------------------

    stroke_widths = get_stroke_widths(root)

    if not stroke_widths:
        raise ValueError(
            "No explicit stroke-width values were found."
        )

    max_stroke = max(stroke_widths)

    if max_stroke <= 0:
        raise ValueError(
            "Maximum stroke width must be greater than zero."
        )

    # --------------------------------------------------------------
    # Calculate scale.
    # --------------------------------------------------------------

    scale = target_stroke / max_stroke

    print(
        f"  Maximum stroke: {max_stroke:g}"
    )

    print(
        f"  Scale factor:   {scale:.8g}"
    )

    # --------------------------------------------------------------
    # Get current viewBox.
    # --------------------------------------------------------------

    dims = get_svg_dimensions(root)

    if dims is None:
        raise ValueError(
            "Could not determine SVG dimensions."
        )

    x, y, width, height = dims

    # --------------------------------------------------------------
    # Create scaling group.
    # --------------------------------------------------------------

    group = ET.Element(
        f"{{{SVG_NS}}}g",
        {
            "id": SCALING_GROUP_ID,
            "transform": f"scale({scale:.15g})",
        },
    )

    # Move existing SVG content into the group.
    children = list(root)

    for child in children:

        root.remove(child)
        group.append(child)

    root.append(group)

    # --------------------------------------------------------------
    # Scale viewBox.
    # --------------------------------------------------------------

    root.attrib["viewBox"] = (
        f"{x * scale:.15g} "
        f"{y * scale:.15g} "
        f"{width * scale:.15g} "
        f"{height * scale:.15g}"
    )

    # --------------------------------------------------------------
    # Scale physical dimensions if they exist.
    # --------------------------------------------------------------

    if "width" in root.attrib:

        original = numeric_value(
            root.attrib["width"]
        )

        if original is not None:

            root.attrib["width"] = (
                f"{original * scale:.15g}px"
            )

    if "height" in root.attrib:

        original = numeric_value(
            root.attrib["height"]
        )

        if original is not None:

            root.attrib["height"] = (
                f"{original * scale:.15g}px"
            )

    return scale


# ======================================================================
# Combined standardization
# ======================================================================

def standardize_svgs(
    folder_path: str,
    target_path: str,
    target_stroke: float = 1.25,
    target_size: Optional[Tuple[float, float]] = None,
    padding: float = 0.0,
):
    """
    Standardize a collection of SVGs in one operation.

    Each SVG is:

    1. Stripped of a previous scaling group.
    2. Scaled so its maximum stroke width is target_stroke.
    3. Given a common bounding-box size.
    4. Centered within that bounding box.
    5. Given an invisible bounding-box rectangle.

    Parameters
    ----------
    folder_path : str
        Directory containing source SVGs.

    target_path : str
        Directory for standardized SVGs.

    target_stroke : float
        Desired maximum stroke width.

    target_size : tuple(float, float), optional
        Explicit content-area size. If None, the largest dimensions
        among the SVGs are used.

    padding : float
        Uniform padding around the common content area.
    """

    directory = Path(folder_path)
    output_directory = Path(target_path)

    if not directory.is_dir():

        print(
            f"Error: Directory '{folder_path}' does not exist."
        )

        return

    svg_files = list(
        directory.glob("*.svg")
    )

    if not svg_files:

        print(
            f"No SVG files found in '{folder_path}'."
        )

        return

    output_directory.mkdir(
        parents=True,
        exist_ok=True,
    )

    # ==================================================================
    # PASS 1
    #
    # Scale every SVG and determine the largest resulting dimensions.
    # ==================================================================

    print(
        f"Found {len(svg_files)} SVG file(s)."
    )

    print(
        "\nPASS 1: Scaling SVGs..."
    )

    svg_data: Dict[
        Path,
        Tuple[
            ET.ElementTree,
            float,
            float,
            float,
            float,
        ],
    ] = {}

    max_w = 0.0
    max_h = 0.0

    for svg_path in svg_files:

        try:

            tree = ET.parse(
                svg_path
            )

            root = tree.getroot()

            # ----------------------------------------------------------
            # Remove previously generated bounding box.
            # ----------------------------------------------------------

            if remove_existing_bounding_box(root):

                print(
                    f"\n{svg_path.name}: "
                    "removed existing bounding box."
                )

            # ----------------------------------------------------------
            # Scale SVG.
            # ----------------------------------------------------------

            scale_svg(
                root,
                target_stroke=target_stroke,
            )

            # ----------------------------------------------------------
            # Get dimensions AFTER scaling.
            # ----------------------------------------------------------

            dims = get_svg_dimensions(root)

            if dims is None:

                print(
                    f"Skipping {svg_path.name}: "
                    "Could not determine dimensions."
                )

                continue

            x, y, width, height = dims

            svg_data[svg_path] = (
                tree,
                x,
                y,
                width,
                height,
            )

            max_w = max(
                max_w,
                width,
            )

            max_h = max(
                max_h,
                height,
            )

        except ET.ParseError:

            print(
                f"Skipping invalid SVG/XML file: "
                f"{svg_path.name}"
            )

        except ValueError as exc:

            print(
                f"Skipping {svg_path.name}: "
                f"{exc}"
            )

    if not svg_data:

        print(
            "No valid SVGs found to process."
        )

        return

    # ==================================================================
    # Determine common content size.
    # ==================================================================

    if target_size is not None:

        content_width = float(
            target_size[0]
        )

        content_height = float(
            target_size[1]
        )

    else:

        content_width = max_w
        content_height = max_h

    if (
        content_width <= 0
        or content_height <= 0
    ):

        raise ValueError(
            "Target dimensions must be positive."
        )

    # ==================================================================
    # Add padding.
    # ==================================================================

    total_width = (
        content_width
        + 2.0 * padding
    )

    total_height = (
        content_height
        + 2.0 * padding
    )

    print(
        "\nPASS 1 COMPLETE"
    )

    print(
        f"Common content size: "
        f"{content_width:.2f} x "
        f"{content_height:.2f}"
    )

    print(
        f"Padding: {padding:.2f}"
    )

    print(
        f"Final canvas: "
        f"{total_width:.2f} x "
        f"{total_height:.2f}"
    )

    # ==================================================================
    # PASS 2
    #
    # Apply common bounding boxes and center artwork.
    # ==================================================================

    print(
        "\nPASS 2: Applying bounding boxes..."
    )

    modified_count = 0

    for (
        svg_path,
        (
            tree,
            orig_x,
            orig_y,
            orig_w,
            orig_h,
        ),
    ) in svg_data.items():

        root = tree.getroot()

        # --------------------------------------------------------------
        # Calculate centering offset.
        # --------------------------------------------------------------

        pad_x = (
            (content_width - orig_w)
            / 2.0
            + padding
        )

        pad_y = (
            (content_height - orig_h)
            / 2.0
            + padding
        )

        new_x = orig_x - pad_x
        new_y = orig_y - pad_y

        # --------------------------------------------------------------
        # Set common viewBox.
        # --------------------------------------------------------------

        root.attrib["viewBox"] = (
            f"{new_x:.15g} "
            f"{new_y:.15g} "
            f"{total_width:.15g} "
            f"{total_height:.15g}"
        )

        # --------------------------------------------------------------
        # Update physical dimensions if they exist.
        # --------------------------------------------------------------

        if "width" in root.attrib:

            root.attrib["width"] = (
                f"{total_width:.15g}px"
            )

        if "height" in root.attrib:

            root.attrib["height"] = (
                f"{total_height:.15g}px"
            )

        # --------------------------------------------------------------
        # Remove any old bounding box.
        # --------------------------------------------------------------

        remove_existing_bounding_box(
            root
        )

        # --------------------------------------------------------------
        # Add new bounding box.
        # --------------------------------------------------------------

        bbox_rect = ET.Element(
            f"{{{SVG_NS}}}rect",
            {
                "id": "bounding-box",
                "x": f"{new_x:.15g}",
                "y": f"{new_y:.15g}",
                "width": f"{total_width:.15g}",
                "height": f"{total_height:.15g}",
                "fill": "none",
                "pointer-events": "all",
            },
        )

        root.insert(
            0,
            bbox_rect,
        )

        # --------------------------------------------------------------
        # Save.
        # --------------------------------------------------------------

        output_path = (
            output_directory
            / svg_path.name
        )

        tree.write(
            output_path,
            encoding="utf-8",
            xml_declaration=True,
        )

        print(
            f"Standardized: "
            f"{svg_path.name}"
        )

        modified_count += 1

    # ==================================================================
    # Done
    # ==================================================================

    print(
        f"\nDone! "
        f"{modified_count} SVG(s) standardized."
    )

    print(
        f"Maximum stroke width: "
        f"{target_stroke}"
    )

    print(
        f"Final canvas: "
        f"{total_width:.1f} x "
        f"{total_height:.1f}"
    )


# ======================================================================
# Example
# ======================================================================

if __name__ == "__main__":

    folder_to_clean = "./raw"
    folder_to_output = "./svg"

    standardize_svgs(
        folder_to_clean,
        folder_to_output,
        target_stroke=1.25,
        padding=10,
    )

    # Or force a common content area:
    #
    # standardize_svgs(
    #     folder_to_clean,
    #     folder_to_output,
    #     target_stroke=1.25,
    #     target_size=(64.0, 64.0),
    #     padding=8.0,
    # )
